In [1]:
# import dependencies
import pandas as pd
import datetime

In [2]:
# read csv file
jan_2018 = pd.read_csv('Data/JC-201801-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)
feb_2018 = pd.read_csv('Data/JC-201802-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)
march_2018 = pd.read_csv('Data/JC-201803-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)
april_2018 = pd.read_csv('Data/JC-201804-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)
may_2018 = pd.read_csv('Data/JC-201805-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)
june_2018 = pd.read_csv('Data/JC-201806-citibike-tripdata.csv', parse_dates=[0], infer_datetime_format=True)

In [3]:
jan_2018.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1

In [4]:
tripdata_1h18 = jan_2018.append(feb_2018).append(march_2018).append(april_2018).append(may_2018).append(june_2018)
tripdata_1h18.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,932,2018-01-01 02:06:17.5410,2018-01-01 02:21:50.0270,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1
1,550,2018-01-01 12:06:18.0390,2018-01-01 12:15:28.4430,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2
2,510,2018-01-01 12:06:56.9780,2018-01-01 12:15:27.8100,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1
3,354,2018-01-01 14:53:10.1860,2018-01-01 14:59:05.0960,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1
4,250,2018-01-01 17:34:30.1920,2018-01-01 17:38:40.9840,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1

In [5]:
# parse starttime and stoptime columns into separate date/time columns
temp = pd.DatetimeIndex(tripdata_1h18['starttime'])
tripdata_1h18['startDate'] = temp.date
tripdata_1h18['startTime'] = temp.time
del tripdata_1h18['starttime']

temp = pd.DatetimeIndex(tripdata_1h18['stoptime'])
tripdata_1h18['stopDate'] = temp.date
tripdata_1h18['stopTime'] = temp.time
del tripdata_1h18['stoptime']


tripdata_1h18.head()

,tripduration,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startDate,startTime,stopDate,stopTime
0,932,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,1,2018-01-01,02:06:17.541000,2018-01-01,02:21:50.027000
1,550,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,2,2018-01-01,12:06:18.039000,2018-01-01,12:15:28.443000
2,510,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,1,2018-01-01,12:06:56.978000,2018-01-01,12:15:27.810000
3,354,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,1,2018-01-01,14:53:10.186000,2018-01-01,14:59:05.096000
4,250,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,1,2018-01-01,17:34:30.192000,2018-01-01,17:38:40.984000

In [6]:
tripdata_1h18['gender'] = tripdata_1h18['gender'].replace({0:'unknown',
                                           1:'male',
                                           2:'female'})

In [7]:
tripdata_1h18.head(20)

,tripduration,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startDate,startTime,stopDate,stopTime
0,932,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31929,Subscriber,1992,male,2018-01-01,02:06:17.541000,2018-01-01,02:21:50.027000
1,550,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31845,Subscriber,1969,female,2018-01-01,12:06:18.039000,2018-01-01,12:15:28.443000
2,510,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,31708,Subscriber,1946,male,2018-01-01,12:06:56.978000,2018-01-01,12:15:27.810000
3,354,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31697,Subscriber,1994,male,2018-01-01,14:53:10.186000,2018-01-01,14:59:05.096000
4,250,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31861,Subscriber,1991,male,2018-01-01,17:34:30.192000,2018-01-01,17:38:40.984000
5,613,3183,Exchange Place,40.716247,-74.033459,3203,Hamilton Park,40.727596,-74.044247,31859,Subscriber,1982,male,2018-01-01,22:05:05.874000,2018-01-01,22:15:19.419000
6,290,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31694,Subscriber,1958,male,2018-01-02,12:13:51.794000,2018-01-02,12:18:42.107000
7,381,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,31754,Subscriber,1989,female,2018-01-02,12:50:03.343000,2018-01-02,12:56:24.644000
8,318,3183,Exchange Place,40.716247,-74.033459,3275,Columbus Drive,40.718355,-74.038914,31816,Subscriber,1960,male,2018-01-02,13:55:58.243000,2018-01-02,14:01:16.881000
9,1852,3183,Exchange Place,40.716247,-74.033459,3281,Leonard Gordon Park,40.745910,-74.057271,31754,Subscriber,1976,male,2018-01-02,16:55:29.639000,2018-01-02,17:26:22.305000
10,460,3183,Exchange Place,40.716247,-74.033459,3199,Newport Pkwy,40.728745,-74.032108,33463,Subscriber,1989,female,2018-01-02,17:01:50.586000,2018-01-02,17:09:31.434000
11,403,3183,Exchange Place,40.716247,-74.033459,3205,JC Medical Center,40.716540,-74.049638,26256,Subscriber,1985,male,2018-01-02,17:05:12.236000,2018-01-02,17:11:55.263000
12,264,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29616,Subscriber,1974,male,2018-01-02,17:05:12.673000,2018-01-02,17:09:37.402000
13,282,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29681,Subscriber,1976,male,2018-01-02,17:19:56.609000,2018-01-02,17:24:39.534000
14,308,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31949,Subscriber,1968,male,2018-01-02,17:31:45.988000,2018-01-02,17:36:54.359000
15,561,3183,Exchange Place,40.716247,-74.033459,3269,Brunswick & 6th,40.726012,-74.050389,29591,Subscriber,1976,male,2018-01-02,17:32:54.840000,2018-01-02,17:42:16.314000
16,114,3183,Exchange Place,40.716247,-74.033459,3639,Harborside,40.719252,-74.034234,31925,Subscriber,1988,male,2018-01-02,17:37:44.345000,2018-01-02,17:39:38.876000
17,302,3183,Exchange Place,40.716247,-74.033459,3187,Warren St,40.721124,-74.038051,31777,Subscriber,1990,male,2018-01-02,17:54:04.877000,2018-01-02,17:59:06.973000
18,230,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,31763,Subscriber,1992,male,2018-01-02,17:58:24.636000,2018-01-02,18:02:15.632000
19,596,3183,Exchange Place,40.716247,-74.033459,3267,Morris Canal,40.712419,-74.038526,29662,Subscriber,1992,male,2018-01-02,18:05:59.624000,2018-01-02,18:15:55.859000

In [8]:
tripdata_1h18.to_csv('data/tripdata_1h18.csv', header=True)